name: flutter_app_core
description: A package that provides a fully functional core for a themable modulable cross platform app.
version: 0.0.1
author: Martin Danhier
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # iOS style drawer:
  flutter_inner_drawer: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter